### ISSUE TITLE
Creating a "response to blog" page

### ISSUE THREAD

**Issue by IamGiel** [IamGiel/mongo-express-react-node#1]
1. This page must re-render the the orginal bloggers name, photo, subject and the original yap.
2. We need a separate page for all of this when you click on the comment button. 
3. BUT, its a good idea that you mention, to just make the card clickable instead and just remove the comment button.

4. In that page, you can have users click the like button and most importantly write a response blog.  We need it stored in mongodb so that it is persistent.

5.  We will have a like button that increments the yappers page.
6. I will delete the yappers schema and apply the bloggers schema so that the name of the bloggers show up on the yappers page (which is now named sports forum) I will change that.

To help with the task above:  You can look at Blogform.js under client/src/pages/blogForm 
Now, rendering that page should be done with Router which is built in and must be imported using react router, and then you can use that to render your page in the app.js.  That is how the workflow is working.  Make it as a pattern.

**Comment by John95** [comment]
All of these features have now been added.
