### ISSUE TITLE
Make the Date on Reply Readable

### ISSUE THREAD

**Issue by John95** [IamGiel/mongo-express-react-node#13]
Style the div that holds the responses and separate the date. Make it smaller so that it doesn't look hard to read through replies. Simplify the date so that its not in JAVASCRIPT ISO DATE format. We can use MOMENTJS for that.

**Comment by IamGiel** [comment]
John, we can use momentjs to make the dates more readable.  It is still in ISO.

**Comment by John95** [comment]
Dates changed to represent how long ago a comment was made (e.g. 5 days ago).
