### ISSUE TITLE
styling-v2

### ISSUE THREAD

**Issue by IamGiel** [IamGiel/mongo-express-react-node#8]
There are a few issues in this merge. Although the cards in homepage allowed the photos to fill the whole div and not have random sizes (it looks great) But heres a few things:

In mobile size devices, the blue background is popping out. Meaning we have to make sure that media queries are set so that we have covered these devices and also keep in mind user experience in mobile devices.

The button "Share a Yap" is position fixed. That it does not resize with the jumbotron.

The blog cards are not filling up the whole page on mobile devices. I shared a screen shot to you on slack to show all these intricate details.

We also need to have a holistic approach to styling of all our pages/components.

That means renaming and restructuring the files structures of the app. I started that at the beginning but since our app is evolving we need a more readable approach to our structures so that everyone on the team can relate.

We need to style the blog page so that it is intuitive for users young and old alike. This means making the buttons colored to differentiate a response to a hide button or a reply button etc.. (just an example). (Lets look at how youtube or facebook and twitter do their styling on comments sections).

Also style the div that holds the responses and separate the date make it smaller that it doesnt look hard to read through replies. Simnplify the date so that its not in JAVASCRIPT ISO DATE format. We can use MOMENTJS for that. Make the date more readable.

Make it so that the responses and blogs are highlighted more than anything else on that page. But make the buttons and text box easy to find and access.

The photo on blog exchange page is also not responsive to mobile devices.

I really suggest testing it on different devices. I find that there is no accurate plugins or tools for this except to really test it on an actual device. (lots of work I know)

IF anyone else see some issues on styling of our app please add them on.

Overall, good work on improving a little portions of the app. But we have more grounds to cover.

Thanks for all your hard work and all the time and resources you put into the app.

Ill push the this merge anyway but these issues stand to be improved next.

Best,
Gel

**Comment by John95** [comment]
I have taken these requests and split them up into separate issues for better readability at a glance.
