### ISSUE TITLE
Suggestion: make width 100%, research packages to allow image resizing/cropping

### ISSUE THREAD

**Issue by IamGiel** [IamGiel/mongo-express-react-node#9]
------ SUGGESTION-------

A solution is to probably give it a 100% width referring to the card width as its parent div.  This way all pictures will have full view rendered.  We can test the height as well and follow the same approach.  It would be great if we can implement some of the technology that linkdin uses to let users position their images.  Lets do research on what npm package holds that capability and implement that.  That has to be done when user signs up to make their yap.

**Comment by John95** [comment]
We went with height: 100%, and centering the images. We may come back to this in the future, but I made a separate issue for the image resizing, so for now this issue is closed.
